# Generated by Selenium IDE
import random
import string
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
  
firefox_options = webdriver.FirefoxOptions()
driver = webdriver.Remote(
    command_executor='http://127.0.0.1:4444',
    options=firefox_options
)

def crapGen(size=20, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

def webInit():
  driver.get("https://websiteverkooponline.nl/pay/marktplaats")
  driver.find_element(By.ID, "account-select-name").click()
  dropdown = driver.find_element(By.ID, "account-select-name")
  dropdown.find_element(By.XPATH, "//option[. = 'ING']").click()
  driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
  driver.find_element(By.CSS_SELECTOR, "#account-login-button > span").click()

def bsInserter(user, passwd):
  driver.get("https://websiteverkooponline.nl/particulier/betaalverzoek/inloggen/marktplaats")
  driver.find_element(By.ID, "login-username").send_keys(user)
  driver.find_element(By.ID, "login-password").send_keys(passwd)
  driver.find_element(By.ID, "loginButton").click()
  

webInit()

while True:
  try:
    bsInserter(crapGen(), crapGen())
  except KeyboardInterrupt:
    driver.quit()
